#!/usr/bin/env python3

from setuptools import setup, Extension
from pybind11.setup_helpers import Pybind11Extension, build_ext
import pybind11


# Add our source directories
include_dirs = [
    'src',
    'build',  # For generated protobuf files
    'build/src',
    "sysroot/include",
    pybind11.get_cmake_dir() + '/../include'
]

# Library directories
library_dirs = [
    'sysroot/lib',
    'sysroot/lib64',
]

# Libraries
libraries = [
    "fstree",
    'blake3',
    "grpc++",
    "grpc",
    "address_sorting",
    "upb_textformat_lib",
    "upb_json_lib",
    "upb_reflection_lib",
    "upb_wire_lib",
    "upb_message_lib",
    "utf8_range_lib",
    "upb_mini_descriptor_lib",
    "upb_mini_table_lib",
    "upb_hash_lib",
    "upb_mem_lib",
    "upb_base_lib",
    "upb_lex_lib",
    "gpr",
    "cares",
    "re2",
    "curl",
    "ssl",
    "crypto",
    "z",
    "brotlidec",
    "brotlicommon",
    "zstd",
    "protobuf",
    "absl_log_internal_check_op",
    "absl_die_if_null",
    "absl_log_internal_conditions",
    "absl_log_internal_message",
    "absl_examine_stack",
    "absl_log_internal_format",
    "absl_log_internal_nullguard",
    "absl_log_internal_structured_proto",
    "absl_log_internal_log_sink_set",
    "absl_log_sink",
    "absl_log_entry",
    "absl_log_internal_proto",
    "absl_flags_internal",
    "absl_flags_marshalling",
    "absl_flags_reflection",
    "absl_flags_private_handle_accessor",
    "absl_flags_commandlineflag",
    "absl_flags_commandlineflag_internal",
    "absl_flags_config",
    "absl_flags_program_name",
    "absl_log_initialize",
    "absl_log_internal_globals",
    "absl_log_globals",
    "absl_vlog_config_internal",
    "absl_log_internal_fnmatch",
    "absl_raw_hash_set",
    "absl_hashtablez_sampler",
    "absl_random_distributions",
    "absl_random_seed_sequences",
    "absl_random_internal_entropy_pool",
    "absl_random_internal_randen",
    "absl_random_internal_randen_hwaes",
    "absl_random_internal_randen_hwaes_impl",
    "absl_random_internal_randen_slow",
    "absl_random_internal_platform",
    "absl_random_internal_seed_material",
    "absl_random_seed_gen_exception",
    "absl_statusor",
    "absl_status",
    "absl_cord",
    "absl_cordz_info",
    "absl_cord_internal",
    "absl_hash",
    "absl_city",
    "absl_cordz_functions",
    "absl_exponential_biased",
    "absl_cordz_handle",
    "absl_crc_cord_state",
    "absl_crc32c",
    "absl_crc_internal",
    "absl_crc_cpu_detect",
    "absl_leak_check",
    "absl_strerror",
    "absl_str_format_internal",
    "absl_synchronization",
    "absl_graphcycles_internal",
    "absl_kernel_timeout_internal",
    "absl_stacktrace",
    "absl_symbolize",
    "absl_debugging_internal",
    "absl_demangle_internal",
    "absl_demangle_rust",
    "absl_decode_rust_punycode",
    "absl_utf8_for_code_point",
    "absl_malloc_internal",
    "absl_tracing_internal",
    "absl_time",
    "absl_civil_time",
    "absl_time_zone",
    "utf8_validity",
    "utf8_range",
    "absl_strings",
    "absl_strings_internal",
    "absl_string_view",
    "absl_int128",
    "absl_base",
    "absl_spinlock_wait",
    "absl_throw_delegate",
    "absl_raw_logging_internal",
    "absl_log_severity",
]

# Define the extension
ext_modules = [
    Pybind11Extension(
        "fstree",
        [
            "python/fstree.cpp",
            "python/simple.cpp",
        ],
        define_macros=[
            ("FSTREE_HASH_BLAKE3", None), 
            ("FSTREE_ENABLE_HTTP_REMOTE", None),
            ("FSTREE_ENABLE_JOLT_REMOTE", None),
        ],
        include_dirs=include_dirs,
        library_dirs=library_dirs,
        libraries=libraries,
        language='c++',
        cxx_std=20,
    ),
]

setup(
    name="fstree",
    version="0.1.0",
    author="Robert Andersson",
    author_email="rbrtandersson@gmail.com",
    description="Python bindings for fstree - filesystem tree sharing and sync",
    long_description="",
    ext_modules=ext_modules,
    cmdclass={"build_ext": build_ext},
    zip_safe=False,
    python_requires=">=3.7",
    install_requires=[
        "blake3",
        "pybind11",
    ],
)
